### ISSUE TITLE
Text box issue 

### ISSUE THREAD

**Issue by JustChad17** [IsaacLaquerre/GameGrumpsJointJustice#6]
When Brent is saying "We saw him find them in Jory's backpack, why would Ross find them himself if he was the one who stole them?" the text starts to run off the screen and doesn't fit. What should I do to fix it?

**Comment by JustChad17** [comment]
![image](https://user-images.githubusercontent.com/68978630/92411506-2b860780-f116-11ea-9d15-1b18e587b672.png)
There are cases like this where the text box can't fit words in but it looks like there would be room for the word "throwing" in the top text bar, but it puts it below, clogging up space in the text bar. What can I do to change this?

**Comment by IsaacLaquerre** [comment]
For now, just putting a "#" before the word that gets cut off will return to a new line and "fix" this.
