### ISSUE TITLE
Presenting evidence in chapter 5. 

### ISSUE THREAD

**Issue by JustChad17** [IsaacLaquerre/GameGrumpsJointJustice#7]
There's a point where Arin is supposed to present evidence after he says: "We've already heard evidence that proves Jory cared about those coins, and I've got it right here!" and Arin immediately shows the livestream recording. Is this meant to be this way or are we supposed to present the evidence ourselves? Just wanted to make sure in case the coders forgot about that, although if it just a mechanic that hasn't been implemented yet, that's fine.

**Comment by IsaacLaquerre** [comment]
Not implemented yet, but evidence does have to be presented by the player, not the script
