### ISSUE TITLE
Arin has a big-ass head.

### ISSUE THREAD

**Issue by JustChad17** [IsaacLaquerre/GameGrumpsJointJustice#8]
![image](https://user-images.githubusercontent.com/68978630/92412036-49ed0280-f118-11ea-9247-88112ce4197a.png)

When Arin is saying this, his head gets huge. I know it's supposed to be like this, but is there supposed to be a background here or is it supposed to look like this?

**Comment by IsaacLaquerre** [comment]
Normal sprite, no matching background
